spring:
  devtools:
    livereload:
      enabled: true
  profiles:
    include: oauth
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  data:
    mongodb:
      uri: mongodb+srv://dbUser:mLaa3NfNAlaQrsh9@mycluster.dl6bkwj.mongodb.net/test?retryWrites=true&w=majority
      database: mydb
    web:
      pageable:
        default-page-size: 9
        one-indexed-parameters: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: mysql://bd5160b50a6148:3afa5018@us-cdbr-east-06.cleardb.net/heroku_cdbdb1ef6eb6a4e?reconnect=true
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration: #인증
          kakao:
            client-id: e2b91ae7dfb0ac574fad76ba27a9dd0b
            redirect-uri: http://webtoon-review.heroku.com/login/oauth2/code/kakao # http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code #OAuth2는 4가지 Authorization Grant유형이 있다
            scope: profile_nickname, account_email #제공받는 정보
            client-name: Kakao
          naver:
            client-id: k5qHsaP2rog4hgdYbsVM
            client-secret: YyQhLyJ0My
            scope: name,email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://webtoon-review.heroku.com/login/oauth2/code/naver
        provider: #제공자
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize #인증을 요청하는 url
            token_uri: https://kauth.kakao.com/oauth/token #토큰을 요청하는 url
            user-info-uri: https://kapi.kakao.com/v2/user/me #회원정보를 가져오는 url
            user_name_attribute: id #
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize #인증을 요청하는 url
            token_uri: https://nid.naver.com/oauth2.0/token #토큰을 요청하는 url
            user-info-uri: https://openapi.naver.com/v1/nid/me #회원정보를 가져오는 url
            user_name_attribute: response #
logging:level: #띄어쓰기 없음
  org.hibernate.SQL: debug
server:
  port: ${port:8080}
